### ISSUE TITLE
Arrows for some commands should not touch "Upstream repository"

### ISSUE THREAD

**Issue by phil-blain** [ndp/git-cheatsheet#22]
Hi @ndp ! I really like this cheat sheet! It really helped me when I was starting out with Git.

I noticed that the arrow for a few commands end or begin in the "Upstream repository", but they in fact do not communicate with the upstream repository:
- `reset --hard <remote>/<branch>` : this reset the current branch to the commit at the tip of the remote-tracking branch `<remote>/<branch>`. The `<remote>` remote is not fetched. As such, I think this arrow should start in the "Local repository".
- `branch --track new <remote>/<branch>` same thing; this does not communicate with the upstream repository so it should both start and end in the "Local repository".
- ` branch -r` : this lists remote-tracking branches, and does not communicate with the "Upstream repository". It should be in "Local repository".

My point of view is that only commands that talk to the "Upstream repository" should have their arrows touching it. I think it's important for begginers to clearly distinguish between Git commands that are local and Git commands that talk to remote repositories.

Would you accept a PR that would make these changes ?

**Comment by waldyrious** [comment]
@phil-blain how to you suggest differentiating between local branches and local references to remote branches?

**Comment by phil-blain** [comment]
At first thought, I don't think I would.. 
I would just do the changes I suggested above for `reset --hard <remote>/<branch>` and `branch --track new <remote>/<branch>`, and I think I would just remove `branch -r`. There's already `branch` in the "Local repository" column, and its description mentions `-r` so I think it would be enough.

For `reset --hard <remote>/<branch>`  I would change the first sentence of  the description this way: 
~~~diff
- Reset local repo and working tree to match a remote branch. 
+ Reset local repo and working tree to match a remote-tracking branch. 
~~~

Also, for `branch --track <new> <remote>/<branch>`, I would change the command to simply `branch <new> <remote>/<branch>`, since the default behaviour of Git is to setup tracking if the starting point if a remote-tracking branch (see the [`git branch` man page](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---track)). And maybe I would change the description also:
~~~diff
- Create a new local branch that tracks a remote branch.
+ Create a new local branch from a remote-tracking branch.
~~~

**Comment by ndp** [comment]
I'm sorry for my slowness. My notifications got turned off.

These are all good suggestions and I'm incorporating them here: https://github.com/ndp/git-cheatsheet/pull/28
