### ISSUE TITLE
Adding RTL mode for supporting RTL languages.

### ISSUE THREAD

**Issue by amiria703** [ndp/git-cheatsheet#41]
**Is your feature request related to a problem? Please describe.**
Hi! I want to contribute to this project and Persian language, but as it's a RTL language, forcing it to be shown LTR is not a good idea.

**Describe the solution you'd like**
Adding a RTL mode for RTL languages.

**Describe alternatives you've considered**
I don't know what to write here. :/

**Additional context**
![image](https://user-images.githubusercontent.com/54179379/171441544-06c99a62-531f-4af2-8cbd-3956a36fe135.png)
Here, I added `direction: rtl;` for testing the layout.

**Comment by ndp** [comment]
@amiria703 At the command level, is it still RTL, or does that switch to LTR at some point?

**Comment by ndp** [comment]
WIP here https://github.com/ndp/git-cheatsheet/pull/42

**Comment by amiria703** [comment]
> 

@ndp 
What does _command level_ mean? Which part of website?

**Comment by ndp** [comment]
It's ready to try out if you want to start a translation.  There are instructions in this PR 32a1103 .

**Comment by ndp** [comment]
This has been merged into the master branch if anyone wants to take a whack at translating a LTR language. My implementation may not be right, as I'm not sure how this works and don't currently have the language skills to know what is right and wrong. But the basic idea of text being able to be drawn the other way works.
