### ISSUE TITLE
Translate to Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by HenriqueAJNB** [ndp/git-cheatsheet#43]
It would be awesome to see a translation to pt-br just like the other ones (fr, de, etc.). 

I can take this task, as soon as I receive some starting guidelines.

I've noticed a JSON file with translation. Would that be enough?

**Comment by ndp** [comment]
I have added some instructions here:

https://github.com/ndp/git-cheatsheet/pull/44/files

But if you have more questions, just ask. If you are only comfortable
translating the JSON, I could take care of the rest.
- Andy

Andy Peterson
http://ndpsoftware.com
Twitter: @ndp8

**Comment by HenriqueAJNB** [comment]
Hi @ndp. I've already opened a PR that, if approved, will close this issue. Thanks for the well detailed instructions!
